pull_request_rules:
- name: Automatically open v1.4 backport PR
  conditions:
    - base=main
    - label="backport-to-v1.4"
  actions:
    backport:
      regexes:
        - "^backport-to-(.*)"
      assignees:
        - "{{ author }}"

- name: Ask to resolve conflict
  conditions:
    - conflict
  actions:
    comment:
      message: This pull request is now in conflict. Could you fix it @{{author}}? 🙏
